spring.application.name=consultaruc

server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/db_ruc
spring.datasource.username=postgres
spring.datasource.password=i2digitalSRL

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-plataform=org.hibernate.dialect.PostgreSQLDialect

